### ISSUE TITLE
Gradient exports

### ISSUE THREAD

**Issue by TravisSpomer** [microsoft/fluentui-token-pipeline#29]
- [x] Support gradients with an arbitrary number of stops in any direction
  - [x] Support the special case where the gradient stops are fixed pixel amounts instead of a percentage
  - [x] Support colors being defined as token references instead of fixed values
- [x] Export gradients in CSS
  - [x] Fixed stops: `linear-gradient()` natively supports `4px` as a stop definition
- [x] Export gradients in WinUI
  - [x] Fixed stops: `LinearGradientBrush` needs `MappingMode="Absolute"` and an appropriate `RotateTransform`
- [x] Add documentation to the site

**Comment by TravisSpomer** [comment]
Here's how you'd define the brush in XAML:

```xaml
<LinearGradientBrush MappingMode="Absolute" StartPoint="0,0" EndPoint="0,4">
    <LinearGradientBrush.RelativeTransform>
        <ScaleTransform ScaleY="-1" CenterY="0.5" />
    </LinearGradientBrush.RelativeTransform>
    <LinearGradientBrush.GradientStops>
        <GradientStop Offset="0" Color="Black" />
        <GradientStop Offset="1.0" Color="#c0c0c0" />
    </LinearGradientBrush.GradientStops>
</LinearGradientBrush>                            
```

And here's how you'd do it in CSS:

```css
.gradient-border
{
    position: relative;

    border-radius: 4px;
    background: linear-gradient(to top, black 0%, #c0c0c0 4px);
}

.gradient-inner
{
    position: absolute;
    left: 1px;
    top: 1px;
    right: 1px;
    bottom: 1px;

    border-radius: 3px;
    background-color: white;
}
```

In CSS, you need to use a set of nested elements: `border-image` can support a gradient, but not rounded corners, so the corners of the element are missing if you try to apply a rounded corner.

```css
.gradient-border-image
{
    position: relative;

    border: 1px solid #c0c0c0;
    border-image: linear-gradient(to top, black 0%, #c0c0c0 4px);
    border-image-slice: 1;
    /* border-radius: 4px; does not help here */
    clip-path: inset(0 round 4px);
}
```

An alternative is to use a pseudo-element, which has the drawbacks of putting the border *outside* of the element, and also introduces potential z-index and layout problems.

```css
.gradient-border-pseudo
{
    position: relative;

    border-radius: 3px;
    background-color: white;
}

.gradient-border-pseudo::before
{
    content: "";
    z-index: -1;
    position: absolute;
    left: -1px;
    top: -1px;
    right: -1px;
    bottom: -1px;

    border-radius: 4px;
    background: linear-gradient(to top, black 0%, #c0c0c0 4px);
}
```
